### ISSUE TITLE
Lucas - weekplan tasklist

### ISSUE THREAD

**Issue by luca2422** [luca2422/Lucas-Modul-2-Weekplan#1]
## Task list for Course 1:

- [x] 1. Life as a Programmer
- [x] 2. Software Development
- [x] 3. Tools of the Trade
- [x] 4. Programming Languages
- [x] 5. Python Show and Tell
- [x] 6. Working with Python
- [x] 7. Exploring Different Languages
- [x] 8. Your first programming job
- [x] Conclusion
- [x] Quiz
- [x] Course 1 completed

## Task list for Course 2:

- [x] 1. Programming Basics
- [x] 2. Programming Syntax
- [x] 3. Variables and Data Types
- [x] 4. Conditional Code
- [x] 5. Modular Code
- [x] Conclusion
- [x] Quiz
- [x] Course 2 completed

## Task list for Course 3:

- [x] 1. Collections
- [x] 2. Iteration
- [x] 3. Using External Code
- [x] 4. Working with Strings
- [x] 5. Planning a Program
- [x] 6. Input and Output
- [x] 7. Debugging
- [x] 8. Object Orientation
- [x] 9. Advanced Topics
- [x] Conclusion
- [x] Quiz
- [x] Course 3 completed
- [x] Final Exam (certification)
